### ISSUE TITLE
Proposal: Adding dark theme

### ISSUE THREAD

**Issue by agilov** [mmcgrana/gobyexample#476] opened 2023-05-20 12:17 UTC
Good day everyone! Often, I find myself reading gobyexample late into the night, sometimes even before going to bed. Given this, I'd like to propose the addition of a dark theme for the site, complete with automatic preference scheme detection, similar to what's in place on go.dev:

<img width="680" alt="go.dev dark mode switch" src="https://github.com/mmcgrana/gobyexample/assets/825624/6075f225-d75f-4b8e-b719-f389e445a4cf">

The actual color scheme can be modeled after the ones used on go.dev or github.com:

<img width="1205" alt="go.dev dark colors" src="https://github.com/mmcgrana/gobyexample/assets/825624/eba4fb9b-56c6-4940-9326-29b5a0076f97">

For the code colors, we can use those from the [Chroma Style Gallery](https://xyproto.github.io/splash/docs/). I recommend the "[github-dark](https://xyproto.github.io/splash/docs/all.html#github-dark)" style:

<img width="646" alt="code theme github-dark" src="https://github.com/mmcgrana/gobyexample/assets/825624/b239b481-bf85-4f54-8871-7ad8f73935cd">

If the maintainers are amenable to this idea, I am more than willing to implement it. It should be a straightforward task.

**Comment by eliben** [comment] 2023-05-20 12:46
Duplicate of #460

**Closed by eliben** 2023-05-20 12:46 UTC

**Comment by agilov** [comment] 2023-05-20 18:50
@eliben, thank you for your response. I understand the concern regarding additional complexity in the frontend code. Having reviewed issue #460, I see how maintaining simplicity has been a priority for gobyexample.

However, I would like to highlight that the proposed feature would only require an additional 61 lines of CSS code, 4 lines of JavaScript, and 1 line of HTML. This is a relatively small addition considering the improved user experience for those who prefer a dark mode, particularly when reading at night.

Moreover, it's worth noting that many official Go resources have already implemented and maintained a dark mode. Having a similar feature on gobyexample could help maintain consistency across Go-related resources.

**Comment by reignmaker** [comment] 2024-02-05 14:20
The lack of the dark theme is the only thing that stops me from reading and recommending gobyexample, sadly.
