### ISSUE TITLE
How about mentioning waitGroup in the Worker Pool example?

### ISSUE THREAD

**Issue by amosshapira** [mmcgrana/gobyexample#166] opened 2017-06-18 07:14 UTC
As far as I follow the Worker Pool example, the only reason it stops on time is because the final loop to print the results is careful to loop exactly 5 times. There is no way for the `worker` routines to close the `results` channel to mark that they are all done.

Perhaps it would be useful to mention the option of `waitGroup` (https://golang.org/pkg/sync/#WaitGroup), which is nicely demonstrated in https://nathanleclaire.com/blog/2014/02/21/how-to-wait-for-all-goroutines-to-finish-executing-before-continuing-part-two-fixing-my-ooops/

(EDIT: Point to an updated blog post with corrected examples)

**Comment by mmcgrana** [comment] 2019-05-29 21:33
@eliben wdyt?

**Comment by eliben** [comment] 2019-05-29 22:00
Sounds like a good idea. I can add it in #233 or do is separately in a follow-up

**Comment by mmcgrana** [comment] 2019-05-29 22:14
Let's add it in #233. I think it help make clear / depend on how/where the new example fits in the overall site.

**Comment by eliben** [comment] 2019-05-29 22:47
FWIW, I think the worker pool example is fine as is, and I wouldn't add a `WaitGroup` to it. *Mentioning* it in the comments may be a good idea, however.

The example is fine because it does what it intends to do in a simple way. We know how many results to expect, so that's how many results we read from a channel. Everything should exist cleanly and not leave goroutines hanging in this case. Note that the number of goroutines is different from the number of jobs - by design since this is a pool. A `WaitGroup` is more idiomatic for waiting for goroutines rather than for jobs, so I don't see a very natural way of incorporating it into the example without over-complicating it.

**Comment by mmcgrana** [comment] 2019-05-29 23:29
Right, I agree on mentioning it but not changing the worker pool example.

It be good to work in somewhere this idea of where a pool vs. a group is appropriate, or perhaps link to something that does, but that's quite subtle so I'm also OK if it's left implicit.

**Comment by eliben** [comment] 2019-05-30 13:29
I think this can be closed, now that #223 was merged

**Closed** 2019-05-30 13:32 UTC
