### ISSUE TITLE
Local Variable Captured by Func Literal in `waitgroups` Example

### ISSUE THREAD

**Issue by AndrewLawrence80** [mmcgrana/gobyexample#535] opened 2024-05-28 09:01 UTC
In the [example](https://github.com/mmcgrana/gobyexample/blob/master/examples/waitgroups/waitgroups.go), the worker call closure captures local variable `i`, which is not recommended.

Original code:

```go
for i := 1; i <= 5; i++ {
	wg.Add(1)

	// Wrap the worker call in a closure that makes sure to tell
	// the WaitGroup that this worker is done. This way the worker
	// itself does not have to be aware of the concurrency primitives
	// involved in its execution.
	go func() {
		defer wg.Done()
		worker(i)
	}()
}
```

Improved code:

```go
for i := 1; i <= 5; i++ {
	wg.Add(1)

	// Wrap the worker call in a closure that makes sure to tell
	// the WaitGroup that this worker is done. This way the worker
	// itself does not have to be aware of the concurrency primitives
	// involved in its execution.
	go func(id int) {
		defer wg.Done()
		worker(id)
	}(i)
}
```

**Comment by eliben** [comment] 2024-05-28 17:55
Duplicate of https://github.com/mmcgrana/gobyexample/issues/520

**Closed by eliben** 2024-05-28 17:55 UTC
