### ISSUE TITLE
"Closing Channels" different output

### ISSUE THREAD

**Issue by dandaka** [mmcgrana/gobyexample#377] opened 2021-07-18 17:51 UTC
## Expected

```
sent job 1
received job 1
sent job 2
received job 2
sent job 3
received job 3
sent all jobs
received all jobs
```

## I see

Different results from time to time, including these

```
sent job 1
received job 1
received job 2
sent job 2
sent job 3
sent all jobs
received job 3
received all jobs
```

```
sent job 1
received job 1
received job 2
sent job 2
sent job 3
sent all jobs
received job 3
received all jobs
```

**Comment by anthony-langford** [comment] 2021-07-29 20:51
I'm seeing a similar output as well.

`sent job 1
sent job 2
sent job 3
sent all jobs
start
received job 1
received job 2
received job 3
received all jobs`

**Comment by anthony-langford** [comment] 2021-07-29 20:56
I'm seeing a different output as well.

```
sent job 1
sent job 2
sent job 3
sent all jobs
start
received job 1
received job 2
received job 3
received all jobs
```

**Comment by eliben** [comment] 2021-08-01 03:46
Duplicate of #307

**Closed by eliben** 2021-08-01 03:46 UTC
